# Away
- id: away
  alias: Trigger - Away
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: not_home
    - platform: state
      entity_id: person.archana_maharjan
      to: not_home
  condition:
    - condition: state
      entity_id: person.ashish_upadhayay
      state: not_home
    - condition: and
      conditions:
        - condition: state
          entity_id: person.archana_maharjan
          state: not_home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lock
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.alarm_panel
  mode: single

# Home
- id: home
  alias: Trigger - Home
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: home
    - platform: state
      entity_id: person.archana_maharjan
      to: home
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm_panel
      state: armed_away
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm_panel
      code: 512
  mode: single

# Sunrise
- id: sunrise
  alias: Routine - Sunrise
  trigger:
    platform: time
    at: '07:00'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.outlet_dishwasher
    - service: cover.open_cover
      data:
        entity_id:
          - cover.aaron_bedroom_blinds_curtain
  mode: single

# Sunset
- id: sunset
  alias: Routine - Sunset
  trigger:
    platform: time
    at: '19:00'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.hallway_ts_3g_switch_1
    - service: cover.close_cover
      data:
        entity_id:
          - cover.aaron_bedroom_blinds_curtain
  mode: single

# Bedtime
- id: bedtime
  alias: Routine - Bedtime
  trigger:
    platform: time
    at: '21:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.night
  mode: single

# Hallway
- id: hallway-motion-on
  alias: Trigger - Hallway MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_zone_2
    to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.hallway_ts_3g_switch_1
  mode: single
- id: hallway-motion-off
  alias: Trigger - Hallway MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_zone_2
    to: 'off'
    for: '00:05:00'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.hallway_ts_3g_switch_1
  mode: single
# Wardrobe
- id: wardrobe-motion-on
  alias: Trigger - Wardrobe MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.wardrobe_ts_1g_switch_1
    - service: light.turn_on
      data:
        entity_id:
          - light.wardrobe_rgb_ls
  mode: single
- id: wardrobe-motion-off
  alias: Trigger - Wardrobe MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'off'
    for: '00:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.wardrobe_ts_1g_switch_1
    - service: light.turn_off
      data:
        entity_id:
          - light.wardrobe_rgb_ls
  mode: single

# Living Room
- id: living-room-motion-on
  alias: Trigger - Living Room MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_zone_3
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.living_room_ts_3g_1_switch_1
        - switch.living_room_ts_3g_1_switch_2
        - switch.living_room_ts_3g_1_switch_3
        - switch.pantry_ts_1g_switch_1
  mode: single

- id: living-room-motion-off
  alias: Trigger - Living Room MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_zone_3
    to: 'off'
    for: '00:10:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.living_room_ts_3g_1_switch_1
        - switch.living_room_ts_3g_1_switch_2
        - switch.living_room_ts_3g_1_switch_3
        - switch.pantry_ts_1g_switch_1
  mode: single

# Button
- id: kbb-pushed
  alias: Trigger - Button PUSHED
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d37cd705-87ec-476f-a30b-4d3d1c334e9e
      value: pushed
  action:
    service: scene.turn_on
    data:
      entity_id: scene.lock
  mode: single

- id: kbb-double
  alias: Trigger - Button DOUBLE
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d37cd705-87ec-476f-a30b-4d3d1c334e9e
      value: double
  action:
    service: scene.turn_on
    data:
      entity_id: scene.night
  mode: single

- id: kbb-held
  alias: Trigger - KB Button HELD
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d45847a9-26f1-4da4-8ef7-82c84700bd23
      value: held
  action:
    service: scene.turn_on
    data:
      entity_id:
        - scene.blackout
  mode: single

# Porch
- id: porch-motion-on
  alias: Trigger - Porch MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '18:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.hallway_ts_3g_switch_1
  mode: single

- id: porch-motion-off
  alias: Trigger - Porch MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'off'
    for: '00:05:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.hallway_ts_3g_switch_1
  mode: single

- id: porch-motion-on-notification
  alias: Notification - Porch MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: '20:00:00'
      after: '08:00:00'
  action:
    - service: media_player.play_media
      data:
        entity_id:
          - media_player.master_bedroom_gnh
          - media_player.living_room_gnm
        media_content_id: http://192.168.86.5:8123/local/notification.mp3
        media_content_type: music
    - delay: '3'
    - service: tts.google_translate_say
      data:
        entity_id:
          - media_player.master_bedroom_gnh
          - media_player.living_room_gnm
        message: Someone is at the front door.
  mode: single
