# Away
- id: away
  alias: Trigger - Away
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: not_home
    - platform: state
      entity_id: person.archana_maharjan
      to: not_home
  condition:
    - condition: state
      entity_id: person.ashish_upadhayay
      state: not_home
    - condition: and
      conditions:
        - condition: state
          entity_id: person.archana_maharjan
          state: not_home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.blackout
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.alarm_panel
  mode: single

# Home
- id: home
  alias: Trigger - Home
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: home
    - platform: state
      entity_id: person.archana_maharjan
      to: home
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm_panel
      state: armed_away
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm_panel
      code: 512
  mode: single

# Sunrise
- id: sunrise
  alias: Routine - Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.dishwasher
    - service: cover.open_cover
      data:
        entity_id:
          - cover.51681463d8bfc0dc7869
  mode: single

# Sunset
- id: sunset
  alias: Routine - Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.2805375584f3eb78a549_3
          - switch.2805375584f3eb78a549_1
    - service: cover.close_cover
      data:
        entity_id:
          - cover.51681463d8bfc0dc7869
  mode: single

# Bedtime
- id: bedtime
  alias: Routine - Bedtime
  trigger:
    platform: time
    at: '21:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.night
  mode: single

# Front Door
- id: front-door-open
  alias: Trigger - Front Door OPEN
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_mp_sensor_contact
    to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78a549_2
  mode: single

- id: front-door-close
  alias: Trigger - Front Door CLOSE
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_mp_sensor_contact
    to: 'off'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78a549_2
  mode: single

# Hallway
- id: hallway-motion-on
  alias: Trigger - Hallway MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78a549_1
  mode: single

- id: hallway-motion-off
  alias: Trigger - Hallway MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_sensor_motion
    to: 'off'
    for: '00:05:00'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78a549_1
  mode: single

# Master Bedroom
- id: master-bedroom-motion-off
  alias: Trigger - Master Bedroom MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.master_bedroom_motion_sensor_motion
    to: 'off'
    for: '00:15:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.master_bedroom_off
  mode: single

- id: 'master-bedroom-hot'
  alias: Trigger - Master Bedroom HOT
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_mp_sensor_temperature_measurement
    above: 22
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: fan.turn_on
    data:
      entity_id: fan.master_bedroom
  mode: single

- id: 'master-bedroom-cold'
  alias: Trigger - Master Bedroom COLD
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_mp_sensor_temperature_measurement
    below: 20
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: fan.turn_off
    data:
      entity_id: fan.master_bedroom
  mode: single

- id: master-bedroom-door-close
  alias: Trigger - Master Bedroom Door CLOSE
  trigger:
    platform: state
    entity_id: binary_sensor.master_bedroom_mp_sensor_contact
    to: 'off'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.dark
  mode: single

# Wardrobe
- id: wardrobe-motion-on
  alias: Trigger - Wardrobe MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.613080753c71bf30c321
  mode: single

- id: wardrobe-motion-off
  alias: Trigger - Wardrobe MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'off'
    for: '00:15:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.613080753c71bf30c321
  mode: single

# Garage Door
- id: garage-door-open
  alias: Trigger - Garage Door OPEN
  trigger:
    platform: state
    entity_id: binary_sensor.garage_mp_sensor_contact
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.61308075ecfabc308206
  mode: single

- id: garage-door-close
  alias: Trigger - Garage Door CLOSE
  trigger:
    platform: state
    entity_id: binary_sensor.garage_mp_sensor_contact
    to: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.61308075ecfabc308206
  mode: single

# Kids Bedroom
- id: kids-bedroom-motion-on
  alias: Trigger - Kids Bedroom MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bedroom_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.kids_bedroom_on
  mode: single

- id: kids-bedroom-motion-off
  alias: Trigger - Kids Bedroom MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bedroom_motion_sensor_motion
    to: 'off'
    for: '00:15:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.kids_bedroom_off
  mode: single

- id: 'kids-bedroom-hot'
  alias: Trigger - Kids Bedroom HOT
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_mp_sensor_temperature_measurement
    above: 22
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.kids_bedroom_fan
  mode: single

- id: 'kids-bedroom-cold'
  alias: Trigger - Kids Bedroom COLD
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_mp_sensor_temperature_measurement
    below: 20
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.kids_bedroom_fan
  mode: single

- id: kbb-pushed
  alias: Trigger - KB Button PUSHED
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: 73d77b47-ff24-4a05-a78b-b1b8c5a5bb17
      value: pushed
  action:
    service: scene.turn_on
    data:
      entity_id: scene.kids_bedroom_on
  mode: single

- id: kbb-double
  alias: Trigger - KB Button DOUBLE
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: 73d77b47-ff24-4a05-a78b-b1b8c5a5bb17
      value: double
  action:
    service: scene.turn_on
    data:
      entity_id: scene.kids_bedroom_off
  mode: single

- id: kbb-held
  alias: Trigger - KB Button HELD
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: 73d77b47-ff24-4a05-a78b-b1b8c5a5bb17
      value: held
  action:
    - service: cover.close_cover
      data:
        entity_id:
          - cover.51681463d8bfc0dc7869
  mode: single

# Kids Bathroom
- id: kids-bathroom-motion-on
  alias: Trigger - Kids Bathroom MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.1745257568c63aeea6d7_2
        - switch.17452575500291642e2b_1
  mode: single

- id: kids-bathroom-motion-off
  alias: Trigger - Kids Bathroom MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    to: 'off'
    for: '00:15:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.1745257568c63aeea6d7_2
        - switch.17452575500291642e2b_1
  mode: single

# Living Room
- id: living-room-motion-on
  alias: Trigger - Living Room MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78abc5_1
        - switch.2805375584f3eb78abc5_2
  mode: single

- id: living-room-motion-off
  alias: Trigger - Living Room MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_motion
    to: 'off'
    for: '00:15:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78abc5_1
        - switch.2805375584f3eb78abc5_2
  mode: single