# Away
- id: away
  alias: Trigger - Away
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: not_home
    - platform: state
      entity_id: person.archana_maharjan
      to: not_home
  condition:
    - condition: state
      entity_id: person.ashish_upadhayay
      state: not_home
    - condition: and
      conditions:
        - condition: state
          entity_id: person.archana_maharjan
          state: not_home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lock
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.alarm_panel
  mode: single

# Home
- id: home
  alias: Trigger - Home
  trigger:
    - platform: state
      entity_id: person.ashish_upadhayay
      to: home
    - platform: state
      entity_id: person.archana_maharjan
      to: home
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm_panel
      state: armed_away
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm_panel
      code: 512
  mode: single

# Sunrise
- id: sunrise
  alias: Routine - Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.dishwasher
    - service: cover.open_cover
      data:
        entity_id:
          - cover.51681463d8bfc0dc7869
  mode: single

# Sunset
- id: sunset
  alias: Routine - Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.2805375584f3eb78a549_3
          - switch.2805375584f3eb78a549_1
    - service: cover.close_cover
      data:
        entity_id:
          - cover.51681463d8bfc0dc7869
  mode: single

# Bedtime
- id: bedtime
  alias: Routine - Bedtime
  trigger:
    platform: time
    at: '21:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.night
  mode: single

# Hallway
- id: hallway-motion-on
  alias: Trigger - Hallway MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_zone_2
    to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78a549_1
  mode: single

- id: hallway-motion-off
  alias: Trigger - Hallway MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_zone_2
    to: 'off'
    for: '00:05:00'
  condition:
    - condition: time
      before: '06:00:00'
      after: '21:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78a549_1
  mode: single
  
# Wardrobe
- id: wardrobe-motion-on
  alias: Trigger - Wardrobe MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.613080753c71bf30c321
  mode: single
  
- id: wardrobe-motion-off
  alias: Trigger - Wardrobe MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.wardrobe_motion_sensor_motion
    to: 'off'
    for: '00:05:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.613080753c71bf30c321
  mode: single

# Kids Bathroom
- id: kids-bathroom-motion-on
  alias: Trigger - Kids Bathroom MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.1745257568c63aeea6d7_2
        - switch.17452575500291642e2b_1
  mode: single

- id: kids-bathroom-motion-off
  alias: Trigger - Kids Bathroom MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    to: 'off'
    for: '00:10:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.1745257568c63aeea6d7_2
        - switch.17452575500291642e2b_1
  mode: single

# Living Room
- id: living-room-motion-on
  alias: Trigger - Living Room MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_zone_3
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '21:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78abc5_1
        - switch.2805375584f3eb78abc5_2
        - switch.2805375584f3eb78abc5_3
  mode: single

- id: living-room-motion-off
  alias: Trigger - Living Room MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_zone_3
    to: 'off'
    for: '00:10:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78abc5_1
        - switch.2805375584f3eb78abc5_2
        - switch.2805375584f3eb78abc5_3
  mode: single

# Garage Door
- id: garage-door-open
  alias: Trigger - Garage Door OPEN
  trigger:
    platform: state
    entity_id: binary_sensor.garage_mp_sensor_contact
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.61308075ecfabc308206
  mode: single

- id: garage-door-close
  alias: Trigger - Garage Door CLOSE
  trigger:
    platform: state
    entity_id: binary_sensor.garage_mp_sensor_contact
    to: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.61308075ecfabc308206
  mode: single

# Button
- id: kbb-pushed
  alias: Trigger - Button PUSHED
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d45847a9-26f1-4da4-8ef7-82c84700bd23
      value: pushed
  action:
    service: light.turn_on
    data:
      entity_id: light.master_bedroom_lamp
  mode: single

- id: kbb-double
  alias: Trigger - Button DOUBLE
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d45847a9-26f1-4da4-8ef7-82c84700bd23
      value: double
  action:
    service: light.turn_off
    data:
      entity_id: light.master_bedroom_lamp
  mode: single

- id: kbb-held
  alias: Trigger - KB Button HELD
  trigger:
    platform: event
    event_type: smartthings.button
    event_data:
      device_id: d45847a9-26f1-4da4-8ef7-82c84700bd23
      value: held
  action:
    service: scene.turn_on
    data:
      entity_id:
        - scene.night
  mode: single

# Porch
- id: porch-motion-on
  alias: Trigger - Porch MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'on'
  condition:
    - condition: time
      before: 06:00:00
      after: '18:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.2805375584f3eb78a549_2
  mode: single

- id: porch-motion-off
  alias: Trigger - Porch MOTION OFF
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'off'
    for: '00:05:00'
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.2805375584f3eb78a549_2
  mode: single

- id: porch-motion-on-notification
  alias: Notification - Porch MOTION ON
  trigger:
    platform: state
    entity_id: binary_sensor.porch_motion_sensor_motion
    to: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id:
          - media_player.master_bedroom
          - media_player.kids_bedroom
        media_content_id: http://192.168.86.5:8123/local/notification.mp3
        media_content_type: music
    - delay: '3'
    - service: tts.google_translate_say
      data:
        entity_id:
          - media_player.master_bedroom
          - media_player.kids_bedroom
        message: Someone is at the front door.
  mode: single
