
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Theme
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /local/card-mod.js
  
# Camera
camera:
  - platform: generic
    name: Driveway Camera
    still_image_url: /local/wyze.png
    stream_source: !secret driveway_camera
  - platform: generic
    name: Garage Camera
    still_image_url: /local/wyze.png
    stream_source: !secret garage_camera

# Sensor
sensor:
  - platform: qnap
    host: 192.168.86.4
    username: !secret qnap_username
    password: !secret qnap_password
    monitored_conditions:
      - cpu_usage
      - memory_percent_used
      - volume_percentage_used
  - platform: google_wifi
    host: 192.168.86.1

# Device Tracker
device_tracker:
  - platform: ping
    hosts:
      ashish_phone: 192.168.86.96
  - platform: ping
    hosts:
      archana_phone: 192.168.86.97

# NESS
ness_alarm:
  host: 192.168.86.46
  port: 2401
  scan_interval:
    seconds: 2
  zones:
    - name: Master Bedroom (Zone 1)
      id: 1
    - name: Hallway (Zone 2)
      id: 2
    - name: Living Room (Zone 3)
      id: 3

automation: !include automations.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml